name: ci
on:
  push: { branches: ["main"] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .commitlintrc.yml
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install pytest-pythonpath
      - name: Lint & Typecheck
        run: |
          ruff check .
          black --check .
          mypy src
      - name: Tests
        run: pytest